ffmpeg-php.lo: /var/www/html/dandan/tools/php-ffmpeg-ext/ffmpeg-php-0.6.0/ffmpeg-php.c
	$(LIBTOOL) --mode=compile $(CC) $(GDLIB_CFLAGS) -I. -I/var/www/html/dandan/tools/php-ffmpeg-ext/ffmpeg-php-0.6.0 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/html/dandan/tools/php-ffmpeg-ext/ffmpeg-php-0.6.0/ffmpeg-php.c -o ffmpeg-php.lo 
ffmpeg_movie.lo: /var/www/html/dandan/tools/php-ffmpeg-ext/ffmpeg-php-0.6.0/ffmpeg_movie.c
	$(LIBTOOL) --mode=compile $(CC) $(GDLIB_CFLAGS) -I. -I/var/www/html/dandan/tools/php-ffmpeg-ext/ffmpeg-php-0.6.0 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/html/dandan/tools/php-ffmpeg-ext/ffmpeg-php-0.6.0/ffmpeg_movie.c -o ffmpeg_movie.lo 
ffmpeg_frame.lo: /var/www/html/dandan/tools/php-ffmpeg-ext/ffmpeg-php-0.6.0/ffmpeg_frame.c
	$(LIBTOOL) --mode=compile $(CC) $(GDLIB_CFLAGS) -I. -I/var/www/html/dandan/tools/php-ffmpeg-ext/ffmpeg-php-0.6.0 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/html/dandan/tools/php-ffmpeg-ext/ffmpeg-php-0.6.0/ffmpeg_frame.c -o ffmpeg_frame.lo 
ffmpeg_errorhandler.lo: /var/www/html/dandan/tools/php-ffmpeg-ext/ffmpeg-php-0.6.0/ffmpeg_errorhandler.c
	$(LIBTOOL) --mode=compile $(CC) $(GDLIB_CFLAGS) -I. -I/var/www/html/dandan/tools/php-ffmpeg-ext/ffmpeg-php-0.6.0 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/html/dandan/tools/php-ffmpeg-ext/ffmpeg-php-0.6.0/ffmpeg_errorhandler.c -o ffmpeg_errorhandler.lo 
ffmpeg_tools.lo: /var/www/html/dandan/tools/php-ffmpeg-ext/ffmpeg-php-0.6.0/ffmpeg_tools.c
	$(LIBTOOL) --mode=compile $(CC) $(GDLIB_CFLAGS) -I. -I/var/www/html/dandan/tools/php-ffmpeg-ext/ffmpeg-php-0.6.0 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/html/dandan/tools/php-ffmpeg-ext/ffmpeg-php-0.6.0/ffmpeg_tools.c -o ffmpeg_tools.lo 
$(phplibdir)/ffmpeg.la: ./ffmpeg.la
	$(LIBTOOL) --mode=install cp ./ffmpeg.la $(phplibdir)

./ffmpeg.la: $(shared_objects_ffmpeg) $(FFMPEG_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_ffmpeg) $(FFMPEG_SHARED_LIBADD)

